### ISSUE TITLE
Overview falsely displays some cores as idle

### ISSUE THREAD

**Issue by ericjbohm** [UIUC-PPL/projections#16]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/483*

---
Overview is dropping many entry methods from its display making cores appear to be idle when they are not.  These appear correctly in timeline.

For example see:
~/work/w256_4k.tracered.rhor1.t22

If you examine the interval 15.123s-16.884s (saved) for cores 2664 to 2689 (as shown in attached screen shots) the overview looks wildly different from the compact timeline.  

![BadOverview2664-2689](https://user-images.githubusercontent.com/1772435/63629882-f9713880-c5da-11e9-9959-6e719d4d5988.png)

![CorrectTimeline26642689](https://user-images.githubusercontent.com/1772435/63629883-f9713880-c5da-11e9-96e9-5dcbe089b83b.png)

**Comment by pplimport** [comment]
*Original author: Anonymous*
*Original date: 2014-05-02 18:06:03*

---
Test

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-05-02 18:23:58*

---
Delegate this task to Maxx. He has been actively working on idle display timeline.

**Comment by pplimport** [comment]
*Original author: Maxx Macica*
*Original date: 2014-05-21 18:53:40*

---
I think I've fixed the issue, but I just wanted to explain what I've done.

First off I fixed two small issues that weren't listed on Redmine. One was that the processor number in the bottom left corner of the Overview was always wrong. The second was that the utilization view was trying to use an "idleData" array that was never initialized, so I implemented that to stop a bunch of null pointer exceptions.

For this issue, the reason that so many entry methods weren't showing up had to do with the way that nestingLevels were used by LogReader to decide whether or not to add begin_processing events to the Overview. Previously, if the nestingLevel was greater than one, or multiple begin_processing signals happened before an end_processing signal, then the LogReader would only count that first begin_processing signal. For example, the hello.sts test example has a max nestingLevel of 1, so it always looked correct, a 64-processor NAMD example I've been testing with has a maximum of 2, so the difference was too small to see, and this OpenAtom example has a maximum of 17 for processors 2664-2689, which caused it to look wildly different. Timeline uses LogLoader which actually creates "pretend" end_processing events whenever one is missing, which is why they all appear in Timeline and not Overview. Since Time Profile Graph also uses LogReader, it also looked wildly different from Timeline.

I replaced nestingLevel with an isProcessing boolean like LogLoader uses and added the checks for when a begin event had no end event. There was also an issue when the last begin event of a .log file has no end event, resulting in an extremely stretched out entry in the Overview, but that has been fixed. Attached are some before and after pictures.

This code will change the Overview for any result that reached a nestingLevel greater than 1, so some old Overviews might look different. I think this version should be more accurate though. If you notice anything wrong let me know!

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-06-02 16:12:35*

---
Eric, 

Can you test openAtom logs to see whether this fix works as you want?

You can checkout by 
git fetch http://jessie`charm.cs.uiuc.edu/gerrit/projections refs/changes/43/243/5 && git checkout FETCH_HEAD

After you verified,  I will approve it.

**Comment by ericjbohm** [comment]
*Original date: 2014-06-02 21:10:00*

---
As far as I can tell this does fix the bug of falsely reporting idle time when there is real activity.  However, the fix seems to have introduced a new bug.  Charm message overhead is not reported at all.  All non entry method times are shown as idle.

**Comment by pplimport** [comment]
*Original author: Maxx Macica*
*Original date: 2014-06-03 16:45:12*

---
Eric, when you have time can you post a picture or explain what you mean by overhead not being reported? On my end I can see overhead in the overview where it appears on the timeline, but maybe I'm missing something.

**Comment by ericjbohm** [comment]
*Original date: 2014-06-03 20:51:38*

---
Using the projections built based on that branch, neither timeline nor overview display any overhead.  This used to be rendered as "black" time consumed by message processing.  See attached screenshot.

**Comment by pplimport** [comment]
*Original author: Maxx Macica*
*Original date: 2014-06-03 22:12:47*

---
I've attached a screenshot, on the left is the Overview and Timeline display before the fix, and on the right side is the after display. I hid all entries except for overhead, and it looks the same before and after. When I fixed this bug, I didn't change the way timeline was displayed at all, so I'm not sure how overhead wouldn't be appearing there. Also if you look at the Overview on the right, the cursor is pointing to an overhead section and it displays "Overhead" in the corner, so overhead is still displayed. Are you talking about something else that I'm just not seeing?

**Comment by ericjbohm** [comment]
*Original date: 2014-06-03 22:23:36*

---
Ok, I see it now.  The problem is in my memory of what these usually look like.  In this particular case the trace was made after I hacked charm to enable tracing of the reduction framework.  So it shows up in orange blocks here that are normally large tracts of black overhead in the [notrace] case.  Mea culpa.  

Fix is good, go ahead.
