### ISSUE TITLE
Timeline Color Selection from Non-Default State Not Working 

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/projections#30]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/703*

---
For the timeline view, when a non-default color scheme (e.g. color by frequency) is chosen, doing manual color selection does not change the color of entry points on the timeline.

**Comment by pplimport** [comment]
*Original author: Keshav Santhanam*
*Original date: 2015-11-13 20:09:45*

---
When user clicks "Change Entry Point Color", MainWindow.runObject[data.myRun].setEntryColor is called from the actionListener and updates entryColor[entryIndex] correctly. However, the repainting process is then kicked off and the determineColor method in EntryMethodObject ends up resetting entryColor[entryIndex]. The colors remain updated if the final else block simply returns the existing value of MainWindow.runObject[data.myRun].entryColors[entryIndex] instead of colToSave. However, this might not be the desired behavior as the colToSave variable is completely ignored.

**Comment by rbuch** [comment]
*Original date: 2018-11-01 05:30:37*

---
Unable to reproduce on latest version of Projections.
